# Generated by Django 2.2.11 on 2020-03-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forgalmazo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cim', models.CharField(max_length=200)),
                ('telefon', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hatas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('megjegyzesek', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hozzavalo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mennyiseg', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Korosztaly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Olaj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kep', models.CharField(max_length=200)),
                ('mese', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('notes', models.TextField()),
                ('hatasok', models.ManyToManyField(to='book.Hatas')),
                ('hozzavalok', models.ManyToManyField(to='book.Hozzavalo')),
            ],
        ),
        migrations.AddField(
            model_name='hozzavalo',
            name='olaj',
            field=models.ForeignKey(on_delete=None, to='book.Olaj'),
        ),
        migrations.AddField(
            model_name='hatas',
            name='korosztaly',
            field=models.ForeignKey(on_delete=None, to='book.Korosztaly'),
        ),
        migrations.CreateModel(
            name='Forgalmazas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiszereles', models.CharField(max_length=200)),
                ('ar', models.IntegerField()),
                ('ceg', models.ForeignKey(on_delete=None, to='book.Forgalmazo')),
                ('olaj', models.ForeignKey(on_delete=None, to='book.Olaj')),
            ],
        ),
    ]
