# Generated by Django 2.2.11 on 2020-03-28 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forgalmazas',
            options={'verbose_name_plural': 'Termékek'},
        ),
        migrations.AlterModelOptions(
            name='forgalmazo',
            options={'verbose_name_plural': 'Forgalmazók'},
        ),
        migrations.AlterModelOptions(
            name='hatas',
            options={'verbose_name_plural': 'Hatások'},
        ),
        migrations.AlterModelOptions(
            name='olaj',
            options={'verbose_name_plural': 'Olajok'},
        ),
        migrations.AlterModelOptions(
            name='recept',
            options={'verbose_name_plural': 'Receptek'},
        ),
    ]
