# Generated by Django 2.2.11 on 2020-03-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgalmazo',
            name='webpage',
            field=models.CharField(default='', max_length=200),
        ),
    ]
