# Generated by Django 2.2.11 on 2020-03-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20200328_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hatas',
            name='korosztaly',
            field=models.CharField(choices=[('csecsemő', 'csecsemő'), ('kisgyerek', 'kisgyerek'), ('nagy gyerek', 'nagy gyerek'), ('felnőtt', 'felnőtt'), ('idős', 'idős'), ('terhes', 'terhes')], default='felnőtt', max_length=200),
        ),
        migrations.DeleteModel(
            name='Korosztaly',
        ),
    ]
