# Generated by Django 2.2.11 on 2020-03-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_forgalmazo_webpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgalmazas',
            name='termeknev',
            field=models.CharField(default='', max_length=200),
        ),
    ]
