# Generated by Django 2.2.11 on 2020-03-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20200329_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hozzavalo',
            name='cseppszam',
        ),
        migrations.RemoveField(
            model_name='hozzavalo',
            name='tipus',
        ),
        migrations.AddField(
            model_name='forgalmazas',
            name='cseppszam',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forgalmazas',
            name='mertekegyseg',
            field=models.CharField(choices=[('1', 'ml'), ('2', 'g'), ('3', 'csepp')], default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='forgalmazas',
            name='tipus',
            field=models.CharField(choices=[('1', 'Növényi Olaj'), ('2', 'Hidralátum'), ('3', 'Kometikai alapanyag'), ('4', '')], default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='recept',
            name='hatas',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='forgalmazo',
            name='cim',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='forgalmazo',
            name='telefon',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='forgalmazo',
            name='webpage',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='hatas',
            name='recept',
            field=models.ForeignKey(on_delete=None, to='book.Olaj'),
        ),
        migrations.AlterField(
            model_name='hozzavalo',
            name='mertekegyseg',
            field=models.CharField(choices=[('1', 'ml'), ('2', 'g'), ('3', 'csepp')], default='1', max_length=2),
        ),
    ]
