# Generated by Django 2.2.11 on 2020-03-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20200329_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgalmazas',
            name='ar',
            field=models.IntegerField(verbose_name='Ár'),
        ),
        migrations.AlterField(
            model_name='forgalmazas',
            name='mertekegyseg',
            field=models.CharField(choices=[('1', 'ml'), ('2', 'g'), ('3', 'csepp')], default='1', max_length=2, verbose_name='Mértékegység'),
        ),
    ]
