# Generated by Django 2.2.11 on 2020-03-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20200329_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgalmazas',
            name='termeknev',
            field=models.CharField(max_length=200, verbose_name='Terméknév'),
        ),
    ]
