# Generated by Django 2.2.11 on 2020-03-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20200329_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hatas',
            old_name='recept',
            new_name='olaj',
        ),
        migrations.AlterField(
            model_name='forgalmazo',
            name='cim',
            field=models.CharField(blank=True, max_length=200, verbose_name='Cím'),
        ),
        migrations.AlterField(
            model_name='forgalmazo',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Név'),
        ),
        migrations.AlterField(
            model_name='hatas',
            name='celcsoport',
            field=models.CharField(choices=[('1', '1-3'), ('2', '3-6'), ('3', '6-12'), ('4', 'felnőtt'), ('5', 'váarndós')], default='4', max_length=2, verbose_name='Célcsoport'),
        ),
        migrations.AlterField(
            model_name='hatas',
            name='megjegyzesek',
            field=models.TextField(verbose_name='Megjegyzések'),
        ),
        migrations.AlterField(
            model_name='hatas',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Hatás'),
        ),
        migrations.AlterField(
            model_name='hozzavalo',
            name='mennyiseg',
            field=models.CharField(max_length=200, verbose_name='mennyiség'),
        ),
        migrations.AlterField(
            model_name='hozzavalo',
            name='olaj',
            field=models.ForeignKey(on_delete=None, to='book.Olaj', verbose_name='Összetevő'),
        ),
        migrations.AlterField(
            model_name='recept',
            name='hatas',
            field=models.TextField(blank=True, verbose_name='Hatás'),
        ),
        migrations.AlterField(
            model_name='recept',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Név'),
        ),
        migrations.AlterField(
            model_name='recept',
            name='notes',
            field=models.TextField(verbose_name='Jegyzetek'),
        ),
        migrations.AlterField(
            model_name='recept',
            name='tipus',
            field=models.CharField(choices=[('1', 'Kozmetikum'), ('2', 'Aromaterápia')], default='2', max_length=2, verbose_name='Típus'),
        ),
    ]
