# Generated by Django 2.2.11 on 2020-03-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_auto_20200329_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olaj',
            name='fajsuj',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fajsúj'),
        ),
        migrations.AlterField(
            model_name='olaj',
            name='latin_nev',
            field=models.CharField(blank=True, max_length=200, verbose_name='Latin név'),
        ),
        migrations.AlterField(
            model_name='olaj',
            name='magyar_nev',
            field=models.CharField(max_length=200, verbose_name='Magyar név'),
        ),
        migrations.AlterField(
            model_name='olaj',
            name='tipus',
            field=models.CharField(choices=[('1', 'Növényi Olaj'), ('2', 'Hidralátum'), ('3', 'Kometikai alapanyag'), ('4', '')], default='1', max_length=2, verbose_name='Típus'),
        ),
    ]
