# Generated by Django 2.2.11 on 2020-03-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20200329_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kemia_focsoport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=200, verbose_name='Név')),
            ],
            options={
                'verbose_name': 'Kémia főcsoport',
                'verbose_name_plural': 'Kémia főcsoportok',
            },
        ),
        migrations.CreateModel(
            name='Kemia_alcsoport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=200, verbose_name='Név')),
                ('test_focsoport', models.ForeignKey(default=None, on_delete=None, to='book.Kemia_focsoport', verbose_name='Kémia főcsoport')),
            ],
            options={
                'verbose_name': 'Kémia alcsoport',
                'verbose_name_plural': 'Kémia alcsoportok',
            },
        ),
        migrations.CreateModel(
            name='Kemia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szazalek', models.IntegerField(blank=True)),
                ('alcsoport', models.ForeignKey(on_delete=None, to='book.Kemia_alcsoport', verbose_name='Kémia')),
                ('olaj', models.ForeignKey(on_delete=None, to='book.Olaj')),
            ],
            options={
                'verbose_name': 'Kémia',
                'verbose_name_plural': 'Kémia',
            },
        ),
    ]
