# Generated by Django 2.2.11 on 2020-03-29 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_kemia_kemia_alcsoport_kemia_focsoport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kemia_alcsoport',
            old_name='test_focsoport',
            new_name='focsoport',
        ),
    ]
