# Generated by Django 2.2.11 on 2020-03-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_auto_20200329_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerapiasHatas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=200, verbose_name='Név')),
                ('mese', models.TextField(blank=True)),
                ('erosseg', models.IntegerField()),
                ('olaj', models.ForeignKey(on_delete=None, to='book.Olaj')),
            ],
            options={
                'verbose_name': 'Terápiás hatás',
                'verbose_name_plural': 'Terápiás hatások',
            },
        ),
        migrations.CreateModel(
            name='AltalanosTulajdonsagok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=200, verbose_name='Név')),
                ('mese', models.TextField(blank=True)),
                ('erosseg', models.IntegerField()),
                ('olaj', models.ForeignKey(on_delete=None, to='book.Olaj')),
            ],
            options={
                'verbose_name': 'Áltlalános tulajdonság',
                'verbose_name_plural': 'Általános tulajdonságok',
            },
        ),
    ]
