# Generated by Django 2.2.11 on 2020-03-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_altalanostulajdonsagok_terapiashatas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hatas',
            options={'verbose_name': 'Terápiás Hatás', 'verbose_name_plural': 'Terápiás Hatások'},
        ),
        migrations.AddField(
            model_name='hatas',
            name='erosseg',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='hatas',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Terápiás Hatás'),
        ),
        migrations.DeleteModel(
            name='TerapiasHatas',
        ),
    ]
