# Generated by Django 2.2.11 on 2020-03-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_auto_20200329_2103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hatas',
            options={'verbose_name': 'Hatás', 'verbose_name_plural': 'Hatások'},
        ),
        migrations.RemoveField(
            model_name='hatas',
            name='erosseg',
        ),
        migrations.AlterField(
            model_name='hatas',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Hatás'),
        ),
        migrations.CreateModel(
            name='TerapiasJavaslat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=200, verbose_name='Név')),
                ('mese', models.TextField(blank=True)),
                ('erosseg', models.IntegerField()),
                ('olaj', models.ForeignKey(on_delete=None, to='book.Olaj')),
            ],
            options={
                'verbose_name': 'Terápiás javaslat',
                'verbose_name_plural': 'Terápiás javaslatok',
            },
        ),
    ]
