# Generated by Django 2.2.11 on 2020-03-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_auto_20200329_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltalanosTulajdonsag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erosseg', models.IntegerField(verbose_name='erősség')),
            ],
        ),
        migrations.CreateModel(
            name='AltalanosTulajdonsagFajta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=200, verbose_name='Név')),
                ('mese', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Áltlalános tulajdonság fajta',
                'verbose_name_plural': 'Általános tulajdonság fajták',
            },
        ),
        migrations.CreateModel(
            name='TerapiasJavaslatFajta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=200, verbose_name='Név')),
                ('mese', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Terápiás javaslat fajta',
                'verbose_name_plural': 'Terápiás javaslat fajták',
            },
        ),
        migrations.RemoveField(
            model_name='terapiasjavaslat',
            name='mese',
        ),
        migrations.RemoveField(
            model_name='terapiasjavaslat',
            name='nev',
        ),
        migrations.AlterField(
            model_name='terapiasjavaslat',
            name='erosseg',
            field=models.IntegerField(verbose_name='erősség'),
        ),
        migrations.DeleteModel(
            name='AltalanosTulajdonsagok',
        ),
        migrations.AddField(
            model_name='altalanostulajdonsag',
            name='alttul',
            field=models.ForeignKey(on_delete=None, to='book.AltalanosTulajdonsagFajta', verbose_name='Általános tulajdonság'),
        ),
        migrations.AddField(
            model_name='altalanostulajdonsag',
            name='olaj',
            field=models.ForeignKey(on_delete=None, to='book.Olaj'),
        ),
        migrations.AddField(
            model_name='terapiasjavaslat',
            name='terjav',
            field=models.ForeignKey(default=None, on_delete=None, to='book.TerapiasJavaslatFajta', verbose_name='Terápiás Javaslat'),
            preserve_default=False,
        ),
    ]
