# Generated by Django 2.2.11 on 2020-03-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_auto_20200330_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hatas',
            options={'verbose_name': 'Összetevő Hatás', 'verbose_name_plural': 'Összetevő Hatások'},
        ),
        migrations.AlterField(
            model_name='olaj',
            name='fajsuj',
            field=models.FloatField(blank=True, null=True, verbose_name='Fajsúj'),
        ),
    ]
