# Generated by Django 2.2.11 on 2020-03-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_auto_20200330_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olaj',
            name='jegy',
            field=models.CharField(blank=True, choices=[('FEJJEGY', 'FEJJEGY'), ('SZÍVJEGY', 'SZIVJEGY'), ('3', 'Alapillat')], max_length=10),
        ),
        migrations.AlterField(
            model_name='recept',
            name='tipus',
            field=models.CharField(choices=[('Kozmetikum', 'Kozmetikum'), ('Aromaterápia', 'Aromaterápia')], default='2', max_length=20, verbose_name='Típus'),
        ),
    ]
